# Generated by Django 5.2.11 on 2026-02-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age_range',
            field=models.CharField(blank=True, choices=[('18-22', '18〜22歳'), ('23-27', '23〜27歳'), ('28-32', '28〜32歳'), ('33-37', '33〜37歳'), ('38-42', '38〜42歳'), ('43-47', '43〜47歳'), ('48-52', '48〜52歳'), ('53+', '53歳以上')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='nickname',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
