# Generated by Django 5.2.11 on 2026-03-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_profile_created_at_profile_bio_profile_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age_range',
            field=models.CharField(choices=[('18-22', '18〜22歳'), ('23-27', '23〜27歳'), ('28-32', '28〜32歳'), ('33-37', '33〜37歳'), ('38-42', '38〜42歳'), ('43-47', '43〜47歳'), ('48-52', '48〜52歳'), ('53+', '53歳以上')], max_length=10),
        ),
    ]
