# Generated by Django 5.2.11 on 2026-03-05 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_app', '0004_post_tags_alter_post_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
