# Generated by Django 5.2.11 on 2026-03-07 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_app', '0010_dmmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dmmessage',
            old_name='user',
            new_name='sender',
        ),
        migrations.AlterField(
            model_name='dmmessage',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='community_app.dmroom'),
        ),
    ]
