# Generated by Django 5.2.11 on 2026-03-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_app', '0013_message_image_message_video_alter_message_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='room_images/'),
        ),
        migrations.AddField(
            model_name='dmmessage',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='room_videos/'),
        ),
    ]
