# Generated by Django 5.2.11 on 2026-03-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_app', '0014_dmmessage_image_dmmessage_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dmmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dm_images/'),
        ),
        migrations.AlterField(
            model_name='dmmessage',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='dm_videos/'),
        ),
    ]
