# Generated by Django 5.2.11 on 2026-03-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_app', '0015_alter_dmmessage_image_alter_dmmessage_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='post_videos/'),
        ),
    ]
