# Generated by Django 5.2.11 on 2026-03-09 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_app', '0016_post_image_post_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
