# Generated by Django 5.2.11 on 2026-03-15 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_app', '0018_alter_post_image_alter_post_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='video',
            field=models.TextField(blank=True, null=True),
        ),
    ]
